### ISSUE TITLE
Document docker image

### ISSUE THREAD

**Issue by jeenbroekstra** [eclipse/rdf4j-doc#60]
either in reference documentation or by adding a link to the download section of the project website (or both).

**Comment by jeenbroekstra** [comment]
followup of eclipse/rdf4j-tools#15

**Comment by jeenbroekstra** [comment]
@barthanssens my docker-foo is rather rusty, so can you help me out with the following: 

1. should we be pushing this docker image to some public docker repo to make it easy to use? And if so, do you know how we should set that up? 
2. what do you think is a good spot to put a link to the README so people can find the docker image? Just on the download section of the website? Or should we put something in the doco instead?

**Comment by barthanssens** [comment]
@jeenbroekstra IMHO the best way would be to add it to the "official" docker hub, as part of the Eclipse project.

I guess the Eclipse Project Management Committee should know more about this, since
a few projects like Eclipse Che and Mosquitto have found their way into this hub (https://hub.docker.com/r/eclipse/)

Eclipse Che puts the docker readme in the dockerfiles subdirectory, and there is the standard short description on the docker hub as well

https://github.com/eclipse/che/tree/master/dockerfiles

**Comment by jeenbroekstra** [comment]
This issue was moved to eclipse/rdf4j#1091
